# Generated by Django 4.1.5 on 2023-01-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='asbn',
            new_name='isbn',
        ),
    ]
