# Generated by Django 4.1.5 on 2023-01-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_asbn_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookauthor',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookauthor',
            old_name='book_id',
            new_name='book',
        ),
    ]
