# Generated by Django 4.1.5 on 2023-01-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_author_id_bookauthor_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='book_id',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
            preserve_default=False,
        ),
    ]
