# Generated by Django 4.1.5 on 2023-02-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookreview_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_at']},
        ),
    ]
