# Generated by Django 4.1.6 on 2023-02-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_photo',
            field=models.ImageField(default='default-user-pic.jpg', upload_to=''),
        ),
    ]
